######################################################
# Akka Service Discovery Redis Config               #
######################################################

akka.discovery {
  redis {
    class = "Aaron.Akka.Discovery.Redis.RedisServiceDiscovery, Aaron.Akka.Discovery.Redis"

    # The public facing IP/host of this node
    # akka.remote.dot-netty.tcp.public-hostname is used if not overridden or empty.
    # if akka.remote.dot-netty.tcp.public-hostname is empty, Dns.GetHostName is used.
    public-hostname = ""

    # The public open akka management port of this node
    # The value will need to be from 1 to 65535, auto-assign port (0) is not supported.
    public-port = 8558

    # The service name assigned to the cluster.
    service-name = "default"

    # The connection string used to connect to Redis
    # MANDATORY FIELD: MUST be provided, else the discovery plugin WILL throw an exception.
    connection-string = "<connection-string>"

    # The time-to-live for Redis keys, defaults to 2 minutes
    # Keys that are not refreshed within this period will auto-expire
    ttl = 2m

    # The time-to-live heartbeat update interval, defaults to 30 seconds
    ttl-heartbeat-interval = 30s

    # The key prefix used for all Redis keys
    key-prefix = "akka:discovery"
  }
}
