name: pr_validation

on:
  push:
    branches:
      - master
      - dev
      - main
  pull_request:
    branches:
      - master
      - dev
      - main

jobs:
  test:
    name: Test-${{matrix.os}}
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: "Checkout"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          lfs: true
          fetch-depth: 0

      - name: "Install .NET SDK"
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7
        with:
          global-json-file: "./global.json"

      - name: "Restore .NET tools"
        run: dotnet tool restore

      - name: "Update release notes"
        shell: pwsh
        run: |
          ./build.ps1

      - name: "dotnet build"
        run: dotnet build -c Release

      - name: "dotnet test (Linux)"
        if: runner.os == 'Linux'
        run: dotnet incrementalist run --config .incrementalist/incrementalist.json -- test -c Release

      - name: "dotnet test (Windows)"
        if: runner.os == 'Windows'
        run: dotnet incrementalist run --config .incrementalist/testsOnly.json -- test -c Release

      - name: "slopwatch"
        run: dotnet slopwatch

      - name: "dotnet pack"
        run: dotnet pack -c Release -o ./bin/nuget